### PR TITLE
PPC64 support

### PR DESCRIPTION
**Pull request by user959**
Adding PPC64/AltiVec support for fastbase64. The work was done under @danlark1 guidance.

### Overview

Makefile compiles code for AVX2 by default as before. To compile for AVX512BW and AltiVec use `make SIMD=AVX512BW` and `make SIMD=ALTIVEC` respectively.

I applied Google style guide to files that I had changed.

### Differences with AVX2

fast_avx2 encoder uses [_mm256_mulhi_epu16](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=3547,4201,5156,5156,3970,301,3993,3959,3547,4950,4996,5799,916,5156,5519,4201,5156,301,3970,5653,5653,4907,5395,4913,3970,5395,4996,5519,5945,4201,3536,3536,3508,3536,4201,5661,4201,3536,3508,3536,3508,3536,3536,4201,5519,5944,5944,5519,5945,3536,4982,27,3536,3965,3970&text=_mm256_mulhi_epu16) ([_mm256_mullo_epi16](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=3547,4201,5156,5156,3970,301,3993,3959,3547,4950,4996,5799,916,5156,5519,4201,5156,301,3970,5653,5653,4907,5395,4913,3970,5395,4996,5519,5945,4201,3536,3536,3508,3536,4201,5661,4201,3536,3508,3536,3508,3536,3536,4201,5519,5944,5944,5519,5945,3536,4982,27,3536,3965,3970,3993&text=_mm256_mullo_epi16)) to shift different parts of `ymm` register differently. AltiVec can do it with [vec_sr](https://www.ibm.com/docs/en/xl-c-and-cpp-linux/13.1.3?topic=functions-vec-sr) ([vec_sl](https://www.ibm.com/docs/en/xl-c-and-cpp-linux/13.1.3?topic=functions-vec-sl)).

fast_avx2 decoder has the following line:

```c
const __m256i merge_ab_and_bc = _mm256_maddubs_epi16(in, _mm256_set1_epi32(0x01400140));
```

It changes each 4 bytes `[00dddddd|00cccccc|00bbbbbb|00aaaaaa]` to `[0000cccc|ccdddddd|0000aaaa|aabbbbbb]`. AltiVec doesn't have similar instruction. I've replaced it with 4 other:

```c
// [00000000|00cccccc|00000000|00aaaaaa]
const v16i c_and_a = vec_and(in, mask);
// [0000cccc|cc000000|0000aaaa|aa000000]
const v16i c_and_a_shifted = vec_sl((v8hu)c_and_a, (v8hu)_mm_set1_epi16(6));
// [00000000|00dddddd|00000000|00bbbbbb]
const v16i d_and_b_shifted = vec_sr((v8hu)in, (v8hu)_mm_set1_epi16(8));
// [0000cccc|ccdddddd|0000aaaa|aabbbbbb]
const v16i cd_and_ab = vec_or(c_and_a_shifted, d_and_b_shifted);
```

but it shouldn't be much worse since [_mm256_maddubs_epi16](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=3547,4201,5156,5156,3970,301,3993,3959,3547,4950,4996,5799,916,5156,5519,4201,5156,301,3970,5653,5653,4907,5395,4913,3970,5395,4996,5519,5945,4201,3536,3536,3508,3536,4201,5661,4201,3536,3508,3536,3508,3536,3536,4201,5519,5944,5944,5519,5945,3536,4982,27,3536,3965,3970,3993,5945,3536&text=_mm256_maddubs_epi16) is likely expensive. Mind that we don't need to mask out `d` and `b`, there will be zeros elsewhere after `vec_sr`.

I've replaced \_mm256_testz_si256(lo, hi) with `vec_any_ne(vec_and(lo, hi), _mm_set1_epi8(0))`.

### Bug in AVX512BW

There was wrong constant in avx512 decoder loop: `while (srclen >= 64)`. It should be 88, because we want to read 64 bytes without `==` at the end and also cover 16 zero bytes that we have at the end of `zmm` register after decoding, which requires 22 bytes. So 64 + 2 + 22 = 88. It didn't work for some input lengths before.

### Performance

Power architecture doesn't have instruction analogous to `rdtsc`, I used `clock_gettime` function to test performance. It has about 60ns overhead on power9, but I wasn't be able to measure overhead to subtract it later - I was getting negative numbers. So for small number of input bytes plot is not representative. Also something strange is happening to linux decoder, though for encoder everything is ok.

power9_dec

Output decoding/encoding txt files have same structure now. I've deleted .gnuplot files for skylake performance, they wouldn't work with new output files and amended ones wouldn't work with old output files. But I made similar files for ice lake CPU performance and tested it.

ice_lake_dec

### CODE REVIEW

**Comment by aqrit** [comment]
For `dec_reshuffle`, I was thinking about skipping the `_mm_madd_epi16` and trying:

```
// Pack 16 6-bit values into 12 bytes
// (wasm doesn't have pmaddubsw (but does have pmaddw))
const v128_t shuf = wasm_i8x16_const(2, 1, 0, 6, 5, 4, 10, 9, 8, 14, 13, 12, -1, -1, -1, -1);
v = wasm_v128_or(wasm_i16x8_shr_u(v, 6), wasm_i16x8_shl(v, 8));   // 00cccccc|dddddd00|00aaaaaa|bbbbbb00
v = wasm_v128_or(wasm_i32x4_shr_u(v, 18), wasm_i32x4_shl(v, 10)); // dddd0000|aaaaaabb|bbbbcccc|ccdddddd
v = wasm_i8x16_swizzle(v, shuf);                                  //       ..|ccdddddd|bbbbcccc|aaaaaabb
```

**Comment by user959** [comment]
I've tried it for ppc64:
```c
in = vec_or(vec_sr((v8hu)in, (v8hu)_mm_set1_epi16(6)),
            vec_sl((v8hu)in, (v8hu)_mm_set1_epi16(8))); // 00cccccc|dddddd00|00aaaaaa|bbbbbb00
in = vec_or(vec_sr((v4su)in, (v4su)_mm_set1_epi32(18)),
            vec_sl((v4su)in, (v4su)_mm_set1_epi32(10))); // dddd0000|aaaaaabb|bbbbcccc|ccdddddd
return vec_perm(in, in, (v16i){2, 1, 0, 6, 5, 4, 10, 9, 8, 14, 13, 12, -1, -1, -1, -1});
```
The performance difference is negligible, but somehow old approach is mostly faster on 0.01ns per input byte. I've tested several times for input lengths up to 10k bytes. Here is file with new minus old perf per input byte: [result.txt](https://github.com/lemire/fastbase64/files/6254380/result.txt). First column is number of bytes.

**Comment by lemire** [comment]
Looks like great work. I had a quick look and I will check it again soon.

**Comment by WojciechMula** [comment]
What a great piece of work. Hats off.

BTW, I'm curious what happened to Linux implementation on Power? This looks weird.

**Comment by user959** [comment]
Thank you. I'm curious too. I haven't figured out it yet, but I've just checked whether the growth stops. It does at about 7ns per input byte.
tmp_dec

**Pull request merged**
